export const CONSUMABLE_CATEGORIES = [
  'Engine Oil',
  'Gear Oil',
  'Hydraulic Oil',
  'Chainsaw Oil',
  'Grease',
  'Fuel',
  'Coolant / Antifreeze',
  'Brake Fluid',
  'Fuel Additive',
  'Air Filter',
  'Oil Filter',
  'Fuel Filter',
  'Spark Plug',
  'Drive Belt',
  'Chain & Bar',
  'Blade',
  'Tyre',
  'Battery',
  'Fasteners',
  'Welding',
  'Cleaning',
  'Other',
];

export const CATEGORY_GROUPS = [
  { label: 'Fluids',    categories: ['Engine Oil','Gear Oil','Hydraulic Oil','Chainsaw Oil','Grease','Fuel','Coolant / Antifreeze','Brake Fluid','Fuel Additive'] },
  { label: 'Filters',   categories: ['Air Filter','Oil Filter','Fuel Filter'] },
  { label: 'Wear Parts',categories: ['Spark Plug','Drive Belt','Chain & Bar','Blade','Tyre','Battery'] },
  { label: 'Workshop',  categories: ['Fasteners','Welding','Cleaning','Other'] },
];

export const CATEGORY_ICON = {
  'Engine Oil':        '🛢️',
  'Gear Oil':          '⚙️',
  'Hydraulic Oil':     '🔧',
  'Chainsaw Oil':      '🪚',
  'Grease':            '🧴',
  'Fuel':              '⛽',
  'Coolant / Antifreeze': '❄️',
  'Brake Fluid':       '🚗',
  'Fuel Additive':     '⚗️',
  'Air Filter':        '💨',
  'Oil Filter':        '🔵',
  'Fuel Filter':       '⬛',
  'Spark Plug':        '⚡',
  'Drive Belt':        '〰️',
  'Chain & Bar':       '🪚',
  'Blade':             '🔪',
  'Tyre':              '🔘',
  'Battery':           '🔋',
  'Fasteners':         '🔩',
  'Welding':           '🔥',
  'Cleaning':          '🧹',
  'Other':             '📦',
};

export const CATEGORY_COLOR = {
  'Engine Oil':        '#e8670a',
  'Gear Oil':          '#c8870a',
  'Hydraulic Oil':     '#a87010',
  'Chainsaw Oil':      '#8b6914',
  'Grease':            '#888',
  'Fuel':              '#e8c20a',
  'Coolant / Antifreeze': '#0a8fe8',
  'Brake Fluid':       '#c80a0a',
  'Fuel Additive':     '#9b59b6',
  'Air Filter':        '#0abfe8',
  'Oil Filter':        '#0a6ee8',
  'Fuel Filter':       '#555',
  'Spark Plug':        '#e8e80a',
  'Drive Belt':        '#8a6a2a',
  'Chain & Bar':       '#5a5a5a',
  'Blade':             '#a0a0a0',
  'Tyre':              '#333',
  'Battery':           '#22c55e',
  'Fasteners':         '#666',
  'Welding':           '#e85a0a',
  'Cleaning':          '#0ae8a0',
  'Other':             '#555',
};

export const CATEGORY_SPECS = {
  'Engine Oil':   [{ key:'viscosity', label:'Viscosity', type:'text', placeholder:'e.g. 10W-40' }, { key:'standard', label:'Standard', type:'text', placeholder:'e.g. API SN, JASO MA2' }],
  'Gear Oil':     [{ key:'viscosity', label:'Viscosity', type:'text', placeholder:'e.g. 80W-90' }],
  'Hydraulic Oil':[{ key:'grade',     label:'Grade',     type:'text', placeholder:'e.g. ISO 46'  }],
  'Chainsaw Oil': [{ key:'type',      label:'Type',      type:'select', options:['Bar & Chain','2-Stroke Mix','Biodegradable'] }],
  'Grease':       [{ key:'nlgi',      label:'NLGI Grade',type:'text', placeholder:'e.g. NLGI 2' }, { key:'type', label:'Type', type:'text', placeholder:'e.g. Lithium, Calcium' }],
  'Fuel':         [{ key:'type',      label:'Fuel Type', type:'select', options:['ULP 91','ULP 95','ULP 98','E10','E85','Diesel','Premium Diesel','Two-Stroke Mix'] }],
  'Coolant / Antifreeze':[{ key:'type', label:'Type', type:'select', options:['Green (IAT)','Red/Pink (OAT)','Blue (HOAT)','Universal'] }, { key:'dilution', label:'Dilution', type:'text', placeholder:'e.g. 50/50' }],
  'Brake Fluid':  [{ key:'dot',       label:'DOT Rating', type:'select', options:['DOT 3','DOT 4','DOT 5','DOT 5.1'] }],
  'Air Filter':   [{ key:'fits',      label:'Fits',      type:'text', placeholder:'e.g. Honda GX160' }],
  'Oil Filter':   [{ key:'fits',      label:'Fits',      type:'text', placeholder:'e.g. 14mm x 1.25' }],
  'Fuel Filter':  [{ key:'fits',      label:'Fits',      type:'text', placeholder:'e.g. inline, 6mm barb' }],
  'Spark Plug':   [{ key:'type',      label:'Part No.',  type:'text', placeholder:'e.g. NGK BR6HS' }, { key:'gap', label:'Gap (mm)', type:'number', placeholder:'e.g. 0.7' }],
  'Drive Belt':   [{ key:'size',      label:'Size',      type:'text', placeholder:'e.g. A42, 4L420' }],
  'Chain & Bar':  [{ key:'pitch',     label:'Pitch',     type:'select', options:['1/4"','3/8" Low Profile','3/8"','0.404"'] }, { key:'gauge', label:'Gauge', type:'select', options:['1.1mm','1.3mm','1.5mm','1.6mm'] }, { key:'driveLinks', label:'Drive Links', type:'number', placeholder:'e.g. 72' }],
  'Blade':        [{ key:'length',    label:'Length (mm)', type:'number', placeholder:'e.g. 400' }, { key:'type', label:'Type', type:'select', options:['Mulching','High-Lift','Low-Lift','Gator','Diamond'] }],
  'Tyre':         [{ key:'size',      label:'Size',      type:'text', placeholder:'e.g. 4.10-6' }],
  'Battery':      [{ key:'voltage',   label:'Voltage',   type:'select', options:['6V','12V','24V','36V','48V'] }, { key:'cca', label:'CCA', type:'number', placeholder:'e.g. 200' }],
};

export const CATEGORY_UNITS = {
  'Engine Oil':        { default:'L',   options:['L','mL','qt','gal'] },
  'Gear Oil':          { default:'L',   options:['L','mL','qt','gal'] },
  'Hydraulic Oil':     { default:'L',   options:['L','mL','qt','gal'] },
  'Chainsaw Oil':      { default:'L',   options:['L','mL','qt','gal'] },
  'Grease':            { default:'kg',  options:['kg','g','lb','cartridge'] },
  'Fuel':              { default:'L',   options:['L','gal','qt'] },
  'Coolant / Antifreeze':{ default:'L', options:['L','mL','qt','gal'] },
  'Brake Fluid':       { default:'mL',  options:['mL','L','oz'] },
  'Fuel Additive':     { default:'mL',  options:['mL','L','oz'] },
  'Air Filter':        { default:'ea',  options:['ea'] },
  'Oil Filter':        { default:'ea',  options:['ea'] },
  'Fuel Filter':       { default:'ea',  options:['ea'] },
  'Spark Plug':        { default:'ea',  options:['ea','pack'] },
  'Drive Belt':        { default:'ea',  options:['ea'] },
  'Chain & Bar':       { default:'ea',  options:['ea'] },
  'Blade':             { default:'ea',  options:['ea','set'] },
  'Tyre':              { default:'ea',  options:['ea','set'] },
  'Battery':           { default:'ea',  options:['ea'] },
  'Fasteners':         { default:'ea',  options:['ea','pack','box','kg'] },
  'Welding':           { default:'kg',  options:['kg','g','spool','ea'] },
  'Cleaning':          { default:'L',   options:['L','mL','ea','spray'] },
  'Other':             { default:'ea',  options:['ea','L','mL','kg','g','m','pack','box'] },
};

export const COMMON_CONSUMABLES = [
  { name:'Engine Oil 10W-40',          category:'Engine Oil',    unit:'L',  spec:{ viscosity:'10W-40', standard:'API SN' } },
  { name:'Engine Oil 5W-30',           category:'Engine Oil',    unit:'L',  spec:{ viscosity:'5W-30',  standard:'API SN' } },
  { name:'2-Stroke Oil',               category:'Engine Oil',    unit:'L',  spec:{ standard:'JASO FD' } },
  { name:'Bar & Chain Oil',            category:'Chainsaw Oil',  unit:'L',  spec:{ type:'Bar & Chain' } },
  { name:'Gear Oil 80W-90',            category:'Gear Oil',      unit:'L',  spec:{ viscosity:'80W-90' } },
  { name:'Hydraulic Oil ISO 46',       category:'Hydraulic Oil', unit:'L',  spec:{ grade:'ISO 46' } },
  { name:'Multi-Purpose Grease',       category:'Grease',        unit:'kg', spec:{ nlgi:'NLGI 2', type:'Lithium' } },
  { name:'ULP 91',                     category:'Fuel',          unit:'L',  spec:{ type:'ULP 91' } },
  { name:'Diesel',                     category:'Fuel',          unit:'L',  spec:{ type:'Diesel' } },
  { name:'Coolant (Green)',            category:'Coolant / Antifreeze', unit:'L', spec:{ type:'Green (IAT)', dilution:'50/50' } },
  { name:'DOT 4 Brake Fluid',          category:'Brake Fluid',   unit:'mL', spec:{ dot:'DOT 4' } },
  { name:'Fuel Stabiliser',            category:'Fuel Additive', unit:'mL', spec:{} },
  { name:'Spark Plug NGK BR6HS',       category:'Spark Plug',    unit:'ea', spec:{ type:'NGK BR6HS', gap:'0.7' } },
  { name:'Spark Plug NGK BPR6ES',      category:'Spark Plug',    unit:'ea', spec:{ type:'NGK BPR6ES', gap:'0.8' } },
  { name:'Drive Belt A42',             category:'Drive Belt',    unit:'ea', spec:{ size:'A42' } },
  { name:'Chainsaw Chain 3/8" LP 56DL',category:'Chain & Bar',   unit:'ea', spec:{ pitch:'3/8" Low Profile', driveLinks:'56' } },
  { name:'Lawn Mower Blade 400mm',     category:'Blade',         unit:'ea', spec:{ length:'400', type:'High-Lift' } },
  { name:'M8 Hex Bolt (pack of 10)',   category:'Fasteners',     unit:'pack', spec:{} },
  { name:'WD-40',                      category:'Cleaning',      unit:'spray', spec:{} },
  { name:'Degreaser',                  category:'Cleaning',      unit:'L',  spec:{} },
];
