// Consumable categories, spec field definitions, units, and common presets.

export const CONSUMABLE_CATEGORIES = [
  'Engine Oil',
  '2-Stroke Oil',
  'Transmission Fluid',
  'Gear Oil',
  'Hydraulic Fluid',
  'Fork Oil',
  'Power Steering Fluid',
  'Brake Fluid',
  'Coolant / Antifreeze',
  'Petrol / Gasoline',
  'Diesel',
  'AdBlue / DEF',
  'Chainsaw Bar Oil',
  'Chain Lube',
  'Grease',
  'Anti-Seize',
  'Thread Locker',
  'RTV Silicone / Gasket Maker',
  'Penetrating Oil',
  'Degreaser',
  'Brake Cleaner',
  'Carb Cleaner',
  'Contact Cleaner',
  'Parts Washer Solvent',
  'Rust Converter',
  'Sandpaper',
  'Grinding Disc',
  'Cut-off Disc',
  'Flap Disc',
  'MIG Wire',
  'TIG Rod',
  'Stick Electrode',
  'Flux Core Wire',
  'Shielding Gas',
  'Air Filter',
  'Oil Filter',
  'Fuel Filter',
  'Shop Towels / Rags',
  'Nitrile Gloves',
  'Cable Ties',
  'Electrical Tape',
  'Masking Tape',
  'Heat Shrink',
  'Other',
];

// Groups for filter bar
export const CATEGORY_GROUPS = [
  { label: 'Oils & Fluids', categories: ['Engine Oil','2-Stroke Oil','Transmission Fluid','Gear Oil','Hydraulic Fluid','Fork Oil','Power Steering Fluid','Chainsaw Bar Oil','Chain Lube'] },
  { label: 'Fuels', categories: ['Petrol / Gasoline','Diesel','AdBlue / DEF'] },
  { label: 'Coolant', categories: ['Coolant / Antifreeze'] },
  { label: 'Brake & Steering', categories: ['Brake Fluid','Power Steering Fluid'] },
  { label: 'Lubricants', categories: ['Grease','Anti-Seize','Thread Locker','Penetrating Oil'] },
  { label: 'Chemicals', categories: ['RTV Silicone / Gasket Maker','Degreaser','Brake Cleaner','Carb Cleaner','Contact Cleaner','Parts Washer Solvent','Rust Converter'] },
  { label: 'Abrasives', categories: ['Sandpaper','Grinding Disc','Cut-off Disc','Flap Disc'] },
  { label: 'Welding', categories: ['MIG Wire','TIG Rod','Stick Electrode','Flux Core Wire','Shielding Gas'] },
  { label: 'Filters', categories: ['Air Filter','Oil Filter','Fuel Filter'] },
  { label: 'Supplies', categories: ['Shop Towels / Rags','Nitrile Gloves','Cable Ties','Electrical Tape','Masking Tape','Heat Shrink','Other'] },
];

export const CATEGORY_ICON = {
  'Engine Oil': '🛢', '2-Stroke Oil': '🛢', 'Transmission Fluid': '🛢',
  'Gear Oil': '🛢', 'Hydraulic Fluid': '🛢', 'Fork Oil': '🛢',
  'Power Steering Fluid': '🛢', 'Chainsaw Bar Oil': '🛢', 'Chain Lube': '🛢',
  'Petrol / Gasoline': '⛽', 'Diesel': '⛽', 'AdBlue / DEF': '⛽',
  'Coolant / Antifreeze': '❄️',
  'Brake Fluid': '🔴',
  'Grease': '🪣', 'Anti-Seize': '🪣', 'Thread Locker': '🔩', 'Penetrating Oil': '💧',
  'RTV Silicone / Gasket Maker': '🔧', 'Degreaser': '⚗️', 'Brake Cleaner': '⚗️',
  'Carb Cleaner': '⚗️', 'Contact Cleaner': '⚗️', 'Parts Washer Solvent': '⚗️',
  'Rust Converter': '⚗️',
  'Sandpaper': '💎', 'Grinding Disc': '💎', 'Cut-off Disc': '💎', 'Flap Disc': '💎',
  'MIG Wire': '🔥', 'TIG Rod': '🔥', 'Stick Electrode': '🔥',
  'Flux Core Wire': '🔥', 'Shielding Gas': '🔥',
  'Air Filter': '🔲', 'Oil Filter': '🔲', 'Fuel Filter': '🔲',
  'Shop Towels / Rags': '📦', 'Nitrile Gloves': '📦', 'Cable Ties': '📦',
  'Electrical Tape': '📦', 'Masking Tape': '📦', 'Heat Shrink': '📦',
  'Other': '📦',
};

export const CATEGORY_COLOR = {
  'Engine Oil': '#e8870a', '2-Stroke Oil': '#e8870a', 'Transmission Fluid': '#e8870a',
  'Gear Oil': '#e8870a', 'Hydraulic Fluid': '#e8870a', 'Fork Oil': '#e8870a',
  'Power Steering Fluid': '#e8870a', 'Chainsaw Bar Oil': '#c8820a', 'Chain Lube': '#c8820a',
  'Petrol / Gasoline': '#c8a800', 'Diesel': '#a08800', 'AdBlue / DEF': '#3d9e50',
  'Coolant / Antifreeze': '#0a8fe8',
  'Brake Fluid': '#c94040',
  'Grease': '#b87020', 'Anti-Seize': '#9a6820', 'Thread Locker': '#3a7bd5',
  'Penetrating Oil': '#8a8a30',
  'RTV Silicone / Gasket Maker': '#6a6a6a', 'Degreaser': '#3d9e50',
  'Brake Cleaner': '#5d9e3d', 'Carb Cleaner': '#5d9e3d', 'Contact Cleaner': '#5d9e3d',
  'Parts Washer Solvent': '#5d9e3d', 'Rust Converter': '#9e5d3d',
  'Sandpaper': '#7a7a7a', 'Grinding Disc': '#7a7a7a', 'Cut-off Disc': '#7a7a7a', 'Flap Disc': '#7a7a7a',
  'MIG Wire': '#c94040', 'TIG Rod': '#c94040', 'Stick Electrode': '#c94040',
  'Flux Core Wire': '#c94040', 'Shielding Gas': '#c94040',
  'Air Filter': '#5a5a5a', 'Oil Filter': '#5a5a5a', 'Fuel Filter': '#5a5a5a',
  'Shop Towels / Rags': '#5a5a5a', 'Nitrile Gloves': '#3a7bd5', 'Cable Ties': '#5a5a5a',
  'Electrical Tape': '#5a5a5a', 'Masking Tape': '#5a5a5a', 'Heat Shrink': '#5a5a5a',
  'Other': '#5a5a5a',
};

// Spec field definitions per category.
// type: 'select' | 'text' | 'number'
export const CATEGORY_SPECS = {
  'Engine Oil': [
    { key: 'viscosity',  label: 'Viscosity',            type: 'select', options: ['0W-20','0W-30','5W-20','5W-30','5W-40','10W-30','10W-40','15W-40','20W-50','SAE 30','SAE 40','SAE 50'] },
    { key: 'oil_type',   label: 'Type',                 type: 'select', options: ['Full Synthetic','Semi-Synthetic','Synthetic Blend','Mineral'] },
    { key: 'standard',   label: 'API / ACEA Standard',  type: 'text',   placeholder: 'e.g. API SP, ACEA A3/B4' },
  ],
  '2-Stroke Oil': [
    { key: 'oil_type',   label: 'Type',       type: 'select', options: ['Full Synthetic','Semi-Synthetic','Mineral'] },
    { key: 'mix_ratio',  label: 'Mix Ratio',  type: 'select', options: ['25:1','32:1','40:1','50:1','100:1'] },
  ],
  'Transmission Fluid': [
    { key: 'fluid_type', label: 'Type', type: 'select', options: ['ATF Dexron VI','ATF Mercon V','ATF+4','CVT Fluid','DSG / DCT Fluid','Manual Gear Oil','Multi-Vehicle ATF'] },
  ],
  'Gear Oil': [
    { key: 'viscosity',  label: 'Viscosity', type: 'select', options: ['70W','75W-90','75W-140','80W-90','80W-140','85W-140'] },
    { key: 'standard',   label: 'GL Rating', type: 'select', options: ['GL-4','GL-5','GL-4/GL-5','MT-1'] },
  ],
  'Hydraulic Fluid': [
    { key: 'iso_grade',  label: 'ISO Grade', type: 'select', options: ['ISO 15','ISO 22','ISO 32','ISO 46','ISO 68','ISO 100'] },
    { key: 'fluid_type', label: 'Type',      type: 'select', options: ['Mineral (AW / HLP)','Biodegradable','Fire-Resistant','HM (Anti-Wear)'] },
  ],
  'Fork Oil': [
    { key: 'weight', label: 'Weight', type: 'select', options: ['2.5W','5W','7.5W','10W','15W','20W'] },
  ],
  'Power Steering Fluid': [
    { key: 'fluid_type', label: 'Type', type: 'select', options: ['PSF (Power Steering Fluid)','ATF Compatible','Mineral','Synthetic','Universal'] },
  ],
  'Brake Fluid': [
    { key: 'dot_rating', label: 'DOT Rating',              type: 'select', options: ['DOT 3','DOT 4','DOT 5','DOT 5.1'] },
    { key: 'dry_bp',     label: 'Dry Boiling Point (°C)',  type: 'number', placeholder: 'e.g. 250' },
    { key: 'wet_bp',     label: 'Wet Boiling Point (°C)',  type: 'number', placeholder: 'e.g. 155' },
  ],
  'Coolant / Antifreeze': [
    { key: 'coolant_type',     label: 'Type',                  type: 'select', options: ['OAT','HOAT','NOAT','IAT (Green / Traditional)','POAT','Hybrid OAT','Universal / All-Vehicle'] },
    { key: 'colour',           label: 'Colour',                type: 'select', options: ['Blue','Green','Red','Yellow','Pink','Orange','Purple','Clear'] },
    { key: 'mix_ratio',        label: 'Mix Ratio',             type: 'select', options: ['Ready-to-Use (50/50 Pre-Mixed)','Concentrate — mix with water','33% Coolant / 67% Water (−20°C)','70% Coolant / 30% Water (−55°C)'] },
    { key: 'freeze_protect',   label: 'Freeze Protection (°C)', type: 'number', placeholder: 'e.g. -37' },
  ],
  'Petrol / Gasoline': [
    { key: 'octane', label: 'Octane Rating (RON)', type: 'select', options: ['91 RON (Regular)','91 RON E10','95 RON (Premium)','95 RON E10','98 RON (Super Premium)','100 RON (Race)','E85 (Flex Fuel)','Avgas 100LL','Avgas UL91'] },
  ],
  'Diesel': [
    { key: 'diesel_type', label: 'Type', type: 'select', options: ['Standard Diesel','Premium Diesel','Biodiesel B5','Biodiesel B20','Biodiesel B100','Marine Diesel','Off-Road / Dyed Diesel'] },
  ],
  'AdBlue / DEF': [
    { key: 'standard', label: 'Standard', type: 'text', placeholder: 'e.g. ISO 22241' },
  ],
  'Chainsaw Bar Oil': [
    { key: 'viscosity', label: 'Viscosity / Season', type: 'select', options: ['Summer (High Viscosity)','Winter (Low Viscosity)','All-Season'] },
    { key: 'bio',       label: 'Biodegradable',      type: 'select', options: ['No','Yes — Vegetable-Based','Yes — Synthetic Ester'] },
  ],
  'Chain Lube': [
    { key: 'lube_type', label: 'Type', type: 'select', options: ['Wet (Rain / Mud)','Dry (Dust / Road)','Ceramic','Wax','All-Weather'] },
  ],
  'Grease': [
    { key: 'nlgi_grade',   label: 'NLGI Grade',  type: 'select', options: ['NLGI 0 (Semi-Fluid)','NLGI 1 (Soft)','NLGI 2 (Standard)','NLGI 3 (Firm)'] },
    { key: 'grease_type',  label: 'Thickener Type', type: 'select', options: ['Lithium','Lithium Complex','Calcium','Calcium Sulfonate','Moly (Molybdenum Disulfide)','Polyurea','Silicone','Marine / Water-Resistant','Wheel Bearing'] },
  ],
  'Anti-Seize': [
    { key: 'compound_type', label: 'Compound',       type: 'select', options: ['Copper','Nickel','Zinc','Silver','Ceramic / High-Temp','Moly (Molybdenum)','Aluminium','Never-Seize'] },
    { key: 'temp_rating',   label: 'Max Temp (°C)', type: 'number', placeholder: 'e.g. 1100' },
  ],
  'Thread Locker': [
    { key: 'strength', label: 'Strength', type: 'select', options: ['Low — Removable (Purple)','Medium — Removable (Blue)','High — Permanent (Red)','High-Strength Penetrating (Green)','Wicking (Green)'] },
    { key: 'colour',   label: 'Colour',   type: 'select', options: ['Purple','Blue','Red','Green'] },
  ],
  'RTV Silicone / Gasket Maker': [
    { key: 'colour',      label: 'Colour / Type', type: 'select', options: ['Black — General Purpose','Grey — Sensor-Safe / Low Odour','Red — High Temp','Blue — Low Tack / Easy Release','Copper — Ultra High Temp','Clear — Food Grade / Aquarium','White — Bathroom / Marine'] },
    { key: 'temp_rating', label: 'Max Temp (°C)', type: 'number', placeholder: 'e.g. 343' },
  ],
  'Penetrating Oil': [
    { key: 'fluid_type', label: 'Brand / Type', type: 'select', options: ['WD-40 (Multi-Use)','WD-40 Specialist Penetrant','PB Blaster','Liquid Wrench','Kroil','CRC 5-56','Inox MX3','Innox MX8','Generic / Workshop'] },
  ],
  'Degreaser': [
    { key: 'degreaser_type', label: 'Type',          type: 'select', options: ['Citrus-Based','Solvent-Based','Water-Based (Aqueous)','Acetone','Isopropyl Alcohol (IPA)','Engine / Heavy-Duty','Foaming / Spray-and-Wipe'] },
    { key: 'concentration',  label: 'Concentration', type: 'select', options: ['Ready-to-Use (RTU)','Concentrate — dilute before use'] },
  ],
  'Brake Cleaner': [
    { key: 'cleaner_type', label: 'Type', type: 'select', options: ['Non-Chlorinated (Safe for O2 sensors)','Chlorinated (Fast-Dry)','Aerosol','Bulk Liquid'] },
  ],
  'Carb Cleaner': [
    { key: 'form', label: 'Form', type: 'select', options: ['Aerosol Spray','Liquid Soak','Ultrasonic Bath Solution'] },
  ],
  'Contact Cleaner': [
    { key: 'contact_type', label: 'Type', type: 'select', options: ['Electronic-Safe — Residue-Free','General Purpose','Electrical Contact Cleaner'] },
  ],
  'Parts Washer Solvent': [
    { key: 'solvent_type', label: 'Type', type: 'select', options: ['Petroleum / Mineral Spirits','Aqueous / Water-Based','Biodegradable / Citrus'] },
  ],
  'Rust Converter': [
    { key: 'rust_type', label: 'Type', type: 'select', options: ['Phosphoric Acid-Based','Tannic Acid-Based','Primer-Converter Combo'] },
  ],
  'Sandpaper': [
    { key: 'grit',     label: 'Grit',          type: 'select', options: ['40','60','80','120','180','240','320','400','600','800','1000','1200','1500','2000','2500','3000'] },
    { key: 'abrasive', label: 'Abrasive',       type: 'select', options: ['Aluminium Oxide','Silicon Carbide','Zirconia Alumina','Ceramic','Garnet'] },
    { key: 'backing',  label: 'Backing / Form', type: 'select', options: ['Sheet (Dry)','Sheet (Wet/Dry)','Roll','Disc (Hook & Loop)','Disc (PSA)','Sponge Block'] },
  ],
  'Grinding Disc': [
    { key: 'diameter_mm',  label: 'Diameter (mm)',   type: 'select', options: ['100','115','125','150','180','230'] },
    { key: 'thickness_mm', label: 'Thickness (mm)',  type: 'text',   placeholder: 'e.g. 6' },
    { key: 'material',     label: 'Material',        type: 'select', options: ['Metal / Mild Steel','Stainless Steel','Aluminium','Masonry / Stone','Multi-Material'] },
  ],
  'Cut-off Disc': [
    { key: 'diameter_mm',  label: 'Diameter (mm)',  type: 'select', options: ['100','115','125','150','180','230'] },
    { key: 'thickness_mm', label: 'Thickness (mm)', type: 'select', options: ['0.8','1.0','1.2','1.6','2.0','2.5','3.0'] },
    { key: 'material',     label: 'Material',       type: 'select', options: ['Metal / Mild Steel','Stainless Steel','Aluminium','Masonry','Multi-Material'] },
  ],
  'Flap Disc': [
    { key: 'diameter_mm', label: 'Diameter (mm)', type: 'select', options: ['100','115','125','150'] },
    { key: 'grit',        label: 'Grit',          type: 'select', options: ['36','40','60','80','120'] },
    { key: 'disc_type',   label: 'Profile',       type: 'select', options: ['T27 (Flat / Level)','T29 (Angled / Aggressive)'] },
    { key: 'abrasive',    label: 'Abrasive',      type: 'select', options: ['Aluminium Oxide','Zirconia Alumina','Ceramic'] },
  ],
  'MIG Wire': [
    { key: 'diameter_mm', label: 'Diameter (mm)',          type: 'select', options: ['0.6','0.8','0.9','1.0','1.2'] },
    { key: 'alloy',       label: 'Alloy / Classification', type: 'select', options: ['ER70S-6 (Mild Steel)','ER308L (304 Stainless)','ER316L (316 Stainless)','ER4043 (Aluminium)','ER5356 (Aluminium — High Strength)','ER80S-D2 (High Tensile)'] },
    { key: 'spool_kg',    label: 'Spool Size (kg)',        type: 'select', options: ['0.5','0.9','1','5','15','20'] },
  ],
  'TIG Rod': [
    { key: 'diameter_mm', label: 'Diameter (mm)',          type: 'select', options: ['1.6','2.4','3.2','4.0'] },
    { key: 'alloy',       label: 'Alloy / Classification', type: 'select', options: ['ER70S-2 (Mild Steel)','ER308L (304 Stainless)','ER316L (316 Stainless)','ER4043 (Aluminium)','ER5356 (Aluminium)','ER2209 (Duplex)','ERNiCr-3 (Inconel)'] },
  ],
  'Stick Electrode': [
    { key: 'diameter_mm',    label: 'Diameter (mm)',    type: 'select', options: ['2.0','2.4','2.5','3.2','4.0','5.0'] },
    { key: 'classification', label: 'Classification',  type: 'select', options: ['E6010','E6011','E6012','E6013 (General Purpose)','E7016','E7018 (Low Hydrogen)','E308L-16 (304 Stainless)','E316L-16 (316 Stainless)','E312 (Dissimilar Metals)'] },
  ],
  'Flux Core Wire': [
    { key: 'diameter_mm', label: 'Diameter (mm)', type: 'select', options: ['0.8','0.9','1.0','1.2'] },
    { key: 'flux_type',   label: 'Type',          type: 'select', options: ['E71T-GS (Gasless / Self-Shielded)','E71T-11 (Gasless / All-Position)','E71T-1C (Gas-Shielded)','E71T-1M (Gas-Shielded / Mixed)'] },
  ],
  'Shielding Gas': [
    { key: 'gas_type',      label: 'Gas Mixture',    type: 'select', options: ['Argon 100% (TIG / Aluminium MIG)','CO₂ 100% (MIG — Deep Penetration)','75% Ar / 25% CO₂ (MIG Steel — Standard)','80% Ar / 20% CO₂','90% Ar / 10% CO₂ (MIG — Cleaner Spatter)','Tri-Mix He/Ar/CO₂ (Stainless)','Pure Helium (TIG — Aluminium)'] },
    { key: 'cylinder_size', label: 'Cylinder Size',  type: 'select', options: ['D (2.0 m³)','E (3.4 m³)','G (8.5 m³)','Swap & Go D','Swap & Go G','Type K (Industrial)'] },
  ],
  'Air Filter': [
    { key: 'form', label: 'Form',              type: 'select', options: ['Panel / Flat','Round (Canister)','Conical / Pod','Oval','Pre-Filter Foam'] },
    { key: 'fits', label: 'Fits (Make/Model)', type: 'text',   placeholder: 'e.g. Honda GX390, Briggs 31' },
  ],
  'Oil Filter': [
    { key: 'fits',   label: 'Fits (Make/Model)', type: 'text', placeholder: 'e.g. Toyota 1HZ, Kubota D1105' },
    { key: 'thread', label: 'Thread Size',       type: 'text', placeholder: 'e.g. M20×1.5, 3/4-16 UNF' },
  ],
  'Fuel Filter': [
    { key: 'fuel_type', label: 'Fuel Type', type: 'select', options: ['Petrol','Diesel','Universal'] },
    { key: 'form',      label: 'Form',      type: 'select', options: ['Inline — Push-Fit','Inline — Threaded','Canister','Spin-On'] },
    { key: 'fits',      label: 'Fits',      type: 'text',   placeholder: 'Optional make / model' },
  ],
  'Shop Towels / Rags': [
    { key: 'material', label: 'Material', type: 'select', options: ['Paper (Blue Shop Roll)','Paper (White)','Cotton Cloth','Microfibre','Disposable Non-Woven'] },
  ],
  'Nitrile Gloves': [
    { key: 'size',          label: 'Size',      type: 'select', options: ['XS','S','M','L','XL','XXL'] },
    { key: 'thickness_mil', label: 'Thickness', type: 'select', options: ['4 mil (Standard)','6 mil (Heavy Duty)','8 mil (Extra Heavy Duty)'] },
  ],
  'Cable Ties': [
    { key: 'length_mm', label: 'Length (mm)', type: 'select', options: ['100','150','200','300','368','450','540','610'] },
    { key: 'colour',    label: 'Colour',      type: 'select', options: ['Natural / White','Black (UV-Stabilised)','Red','Yellow','Green','Blue'] },
  ],
  'Electrical Tape': [
    { key: 'colour',   label: 'Colour',    type: 'select', options: ['Black','Red','Blue','Green','Yellow','White','Orange'] },
    { key: 'width_mm', label: 'Width (mm)', type: 'select', options: ['12','19','25'] },
  ],
  'Masking Tape': [
    { key: 'width_mm',  label: 'Width (mm)', type: 'select', options: ['12','18','24','36','48','75','100'] },
    { key: 'tape_type', label: 'Type',       type: 'select', options: ['General Purpose','Fine Line (Detailing)','High-Temp (Spray / Powder Coat)','Blue (Delicate Surfaces)','Green (Multi-Surface)'] },
  ],
  'Heat Shrink': [
    { key: 'diameter_mm', label: 'Pre-Shrink Ø (mm)', type: 'select', options: ['1.5','2.5','3','4','5','6','8','10','12','16','20','25','32'] },
    { key: 'ratio',       label: 'Shrink Ratio',      type: 'select', options: ['2:1','3:1','4:1'] },
    { key: 'colour',      label: 'Colour',            type: 'select', options: ['Black','Red','Blue','Green','Yellow','White','Clear'] },
  ],
};

// Default unit and unit options per category
export const CATEGORY_UNITS = {
  'Engine Oil':              { default: 'L',         options: ['mL','L','qt','gallon'] },
  '2-Stroke Oil':            { default: 'L',         options: ['mL','L'] },
  'Transmission Fluid':      { default: 'L',         options: ['mL','L','qt'] },
  'Gear Oil':                { default: 'L',         options: ['mL','L','qt'] },
  'Hydraulic Fluid':         { default: 'L',         options: ['mL','L','gallon'] },
  'Fork Oil':                { default: 'mL',        options: ['mL','L'] },
  'Power Steering Fluid':    { default: 'mL',        options: ['mL','L'] },
  'Brake Fluid':             { default: 'mL',        options: ['mL','L'] },
  'Coolant / Antifreeze':    { default: 'L',         options: ['mL','L','gallon'] },
  'Petrol / Gasoline':       { default: 'L',         options: ['L','gallon'] },
  'Diesel':                  { default: 'L',         options: ['L','gallon'] },
  'AdBlue / DEF':            { default: 'L',         options: ['L'] },
  'Chainsaw Bar Oil':        { default: 'L',         options: ['mL','L'] },
  'Chain Lube':              { default: 'mL',        options: ['mL','L'] },
  'Grease':                  { default: 'cartridge', options: ['g','kg','cartridge','tube (500g)','pail (15kg)'] },
  'Anti-Seize':              { default: 'g',         options: ['g','mL','tube (100g)','tin (500g)'] },
  'Thread Locker':           { default: 'mL',        options: ['mL'] },
  'RTV Silicone / Gasket Maker': { default: 'tube', options: ['tube','mL','g'] },
  'Penetrating Oil':         { default: 'can',       options: ['can','mL','L'] },
  'Degreaser':               { default: 'L',         options: ['mL','L','can','gallon'] },
  'Brake Cleaner':           { default: 'can',       options: ['can','mL','L'] },
  'Carb Cleaner':            { default: 'can',       options: ['can','mL'] },
  'Contact Cleaner':         { default: 'can',       options: ['can','mL'] },
  'Parts Washer Solvent':    { default: 'L',         options: ['L','gallon'] },
  'Rust Converter':          { default: 'mL',        options: ['mL','L'] },
  'Sandpaper':               { default: 'sheets',    options: ['sheets','roll','pack'] },
  'Grinding Disc':           { default: 'pcs',       options: ['pcs','pack','box'] },
  'Cut-off Disc':            { default: 'pcs',       options: ['pcs','pack','box'] },
  'Flap Disc':               { default: 'pcs',       options: ['pcs','pack'] },
  'MIG Wire':                { default: 'spool',     options: ['spool','kg'] },
  'TIG Rod':                 { default: 'kg',        options: ['kg','pack (10 rods)','pcs'] },
  'Stick Electrode':         { default: 'kg',        options: ['kg','pack'] },
  'Flux Core Wire':          { default: 'spool',     options: ['spool','kg'] },
  'Shielding Gas':           { default: 'cylinder',  options: ['cylinder'] },
  'Air Filter':              { default: 'pcs',       options: ['pcs'] },
  'Oil Filter':              { default: 'pcs',       options: ['pcs'] },
  'Fuel Filter':             { default: 'pcs',       options: ['pcs'] },
  'Shop Towels / Rags':      { default: 'rolls',     options: ['rolls','pcs','pack','box'] },
  'Nitrile Gloves':          { default: 'box (100)', options: ['box (100)','box (50)','pcs'] },
  'Cable Ties':              { default: 'pack',      options: ['pcs','pack','bag (100)'] },
  'Electrical Tape':         { default: 'rolls',     options: ['rolls'] },
  'Masking Tape':            { default: 'rolls',     options: ['rolls'] },
  'Heat Shrink':             { default: 'm',         options: ['m','pack'] },
  'Other':                   { default: 'pcs',       options: ['pcs','L','mL','kg','g','m','rolls','can','tube','box','pack','spool','set'] },
};

// Common presets for the quick-add dropdown
export const COMMON_CONSUMABLES = [
  { name: 'Engine Oil — 10W-40 Semi-Synthetic',     category: 'Engine Oil',           unit: 'L',         spec: { viscosity: '10W-40',  oil_type: 'Semi-Synthetic' } },
  { name: 'Engine Oil — 5W-30 Full Synthetic',      category: 'Engine Oil',           unit: 'L',         spec: { viscosity: '5W-30',   oil_type: 'Full Synthetic' } },
  { name: 'Engine Oil — 5W-40 Full Synthetic',      category: 'Engine Oil',           unit: 'L',         spec: { viscosity: '5W-40',   oil_type: 'Full Synthetic' } },
  { name: 'Engine Oil — 15W-40 Mineral',            category: 'Engine Oil',           unit: 'L',         spec: { viscosity: '15W-40',  oil_type: 'Mineral' } },
  { name: 'Engine Oil — 20W-50 Mineral',            category: 'Engine Oil',           unit: 'L',         spec: { viscosity: '20W-50',  oil_type: 'Mineral' } },
  { name: '2-Stroke Oil — Full Synthetic 50:1',     category: '2-Stroke Oil',         unit: 'L',         spec: { oil_type: 'Full Synthetic', mix_ratio: '50:1' } },
  { name: '2-Stroke Oil — Mineral 40:1',            category: '2-Stroke Oil',         unit: 'L',         spec: { oil_type: 'Mineral', mix_ratio: '40:1' } },
  { name: 'ATF — Dexron VI',                        category: 'Transmission Fluid',   unit: 'L',         spec: { fluid_type: 'ATF Dexron VI' } },
  { name: 'CVT Fluid',                              category: 'Transmission Fluid',   unit: 'L',         spec: { fluid_type: 'CVT Fluid' } },
  { name: 'Gear Oil — 80W-90 GL-5',                 category: 'Gear Oil',             unit: 'L',         spec: { viscosity: '80W-90', standard: 'GL-5' } },
  { name: 'Gear Oil — 75W-90 GL-4',                 category: 'Gear Oil',             unit: 'L',         spec: { viscosity: '75W-90', standard: 'GL-4' } },
  { name: 'Hydraulic Fluid ISO 46',                 category: 'Hydraulic Fluid',      unit: 'L',         spec: { iso_grade: 'ISO 46', fluid_type: 'Mineral (AW / HLP)' } },
  { name: 'Hydraulic Fluid ISO 68',                 category: 'Hydraulic Fluid',      unit: 'L',         spec: { iso_grade: 'ISO 68', fluid_type: 'Mineral (AW / HLP)' } },
  { name: 'Fork Oil — 5W',                          category: 'Fork Oil',             unit: 'mL',        spec: { weight: '5W' } },
  { name: 'Fork Oil — 10W',                         category: 'Fork Oil',             unit: 'mL',        spec: { weight: '10W' } },
  { name: 'Brake Fluid DOT 4',                      category: 'Brake Fluid',          unit: 'mL',        spec: { dot_rating: 'DOT 4' } },
  { name: 'Brake Fluid DOT 5.1',                    category: 'Brake Fluid',          unit: 'mL',        spec: { dot_rating: 'DOT 5.1' } },
  { name: 'Coolant — Blue OAT Concentrate',         category: 'Coolant / Antifreeze', unit: 'L',         spec: { coolant_type: 'OAT', colour: 'Blue', mix_ratio: 'Concentrate — mix with water' } },
  { name: 'Coolant — Red HOAT Concentrate',         category: 'Coolant / Antifreeze', unit: 'L',         spec: { coolant_type: 'HOAT', colour: 'Red', mix_ratio: 'Concentrate — mix with water' } },
  { name: 'Coolant — Green IAT Concentrate',        category: 'Coolant / Antifreeze', unit: 'L',         spec: { coolant_type: 'IAT (Green / Traditional)', colour: 'Green', mix_ratio: 'Concentrate — mix with water' } },
  { name: 'Coolant — Ready-to-Use (50/50)',         category: 'Coolant / Antifreeze', unit: 'L',         spec: { mix_ratio: 'Ready-to-Use (50/50 Pre-Mixed)' } },
  { name: 'Petrol — 91 RON',                        category: 'Petrol / Gasoline',    unit: 'L',         spec: { octane: '91 RON (Regular)' } },
  { name: 'Petrol — 91 RON E10',                    category: 'Petrol / Gasoline',    unit: 'L',         spec: { octane: '91 RON E10' } },
  { name: 'Petrol — 95 RON Premium',                category: 'Petrol / Gasoline',    unit: 'L',         spec: { octane: '95 RON (Premium)' } },
  { name: 'Petrol — 98 RON Super',                  category: 'Petrol / Gasoline',    unit: 'L',         spec: { octane: '98 RON (Super Premium)' } },
  { name: 'Petrol — E85',                           category: 'Petrol / Gasoline',    unit: 'L',         spec: { octane: 'E85 (Flex Fuel)' } },
  { name: 'Avgas 100LL',                            category: 'Petrol / Gasoline',    unit: 'L',         spec: { octane: 'Avgas 100LL' } },
  { name: 'Diesel — Standard',                      category: 'Diesel',               unit: 'L',         spec: { diesel_type: 'Standard Diesel' } },
  { name: 'Diesel — Premium',                       category: 'Diesel',               unit: 'L',         spec: { diesel_type: 'Premium Diesel' } },
  { name: 'AdBlue / DEF',                           category: 'AdBlue / DEF',         unit: 'L',         spec: { standard: 'ISO 22241' } },
  { name: 'Chainsaw Bar Oil — All-Season',          category: 'Chainsaw Bar Oil',     unit: 'L',         spec: { viscosity: 'All-Season' } },
  { name: 'Chain Lube — Wet',                       category: 'Chain Lube',           unit: 'mL',        spec: { lube_type: 'Wet (Rain / Mud)' } },
  { name: 'Chain Lube — Dry',                       category: 'Chain Lube',           unit: 'mL',        spec: { lube_type: 'Dry (Dust / Road)' } },
  { name: 'Lithium Grease NLGI 2',                  category: 'Grease',               unit: 'cartridge', spec: { nlgi_grade: 'NLGI 2 (Standard)', grease_type: 'Lithium' } },
  { name: 'Moly Grease NLGI 2',                     category: 'Grease',               unit: 'cartridge', spec: { nlgi_grade: 'NLGI 2 (Standard)', grease_type: 'Moly (Molybdenum Disulfide)' } },
  { name: 'Wheel Bearing Grease',                   category: 'Grease',               unit: 'cartridge', spec: { nlgi_grade: 'NLGI 2 (Standard)', grease_type: 'Wheel Bearing' } },
  { name: 'Marine Grease',                          category: 'Grease',               unit: 'cartridge', spec: { grease_type: 'Marine / Water-Resistant' } },
  { name: 'Copper Anti-Seize',                      category: 'Anti-Seize',           unit: 'g',         spec: { compound_type: 'Copper', temp_rating: 1100 } },
  { name: 'Nickel Anti-Seize',                      category: 'Anti-Seize',           unit: 'g',         spec: { compound_type: 'Nickel', temp_rating: 1400 } },
  { name: 'Thread Locker — Blue (Medium)',          category: 'Thread Locker',        unit: 'mL',        spec: { strength: 'Medium — Removable (Blue)', colour: 'Blue' } },
  { name: 'Thread Locker — Red (Permanent)',        category: 'Thread Locker',        unit: 'mL',        spec: { strength: 'High — Permanent (Red)', colour: 'Red' } },
  { name: 'Black RTV Silicone',                     category: 'RTV Silicone / Gasket Maker', unit: 'tube', spec: { colour: 'Black — General Purpose' } },
  { name: 'Grey RTV Silicone (Sensor-Safe)',        category: 'RTV Silicone / Gasket Maker', unit: 'tube', spec: { colour: 'Grey — Sensor-Safe / Low Odour' } },
  { name: 'Copper RTV (Ultra High Temp)',           category: 'RTV Silicone / Gasket Maker', unit: 'tube', spec: { colour: 'Copper — Ultra High Temp', temp_rating: 343 } },
  { name: 'WD-40',                                  category: 'Penetrating Oil',      unit: 'can',       spec: { fluid_type: 'WD-40 (Multi-Use)' } },
  { name: 'Penetrating Oil (PB Blaster)',           category: 'Penetrating Oil',      unit: 'can',       spec: { fluid_type: 'PB Blaster' } },
  { name: 'Degreaser — Citrus Concentrate',         category: 'Degreaser',            unit: 'L',         spec: { degreaser_type: 'Citrus-Based', concentration: 'Concentrate — dilute before use' } },
  { name: 'Engine Degreaser',                       category: 'Degreaser',            unit: 'can',       spec: { degreaser_type: 'Engine / Heavy-Duty', concentration: 'Ready-to-Use (RTU)' } },
  { name: 'Brake Cleaner (Non-Chlorinated)',        category: 'Brake Cleaner',        unit: 'can',       spec: { cleaner_type: 'Non-Chlorinated (Safe for O2 sensors)' } },
  { name: 'Carb Cleaner (Aerosol)',                 category: 'Carb Cleaner',         unit: 'can',       spec: { form: 'Aerosol Spray' } },
  { name: 'Contact Cleaner (Electronic-Safe)',      category: 'Contact Cleaner',      unit: 'can',       spec: { contact_type: 'Electronic-Safe — Residue-Free' } },
  { name: 'Rust Converter',                         category: 'Rust Converter',       unit: 'mL',        spec: { rust_type: 'Phosphoric Acid-Based' } },
  { name: 'Sandpaper — 80 Grit',                   category: 'Sandpaper',            unit: 'sheets',    spec: { grit: '80',  abrasive: 'Aluminium Oxide', backing: 'Sheet (Dry)' } },
  { name: 'Sandpaper — 120 Grit',                  category: 'Sandpaper',            unit: 'sheets',    spec: { grit: '120', abrasive: 'Aluminium Oxide', backing: 'Sheet (Dry)' } },
  { name: 'Sandpaper — 240 Grit Wet/Dry',          category: 'Sandpaper',            unit: 'sheets',    spec: { grit: '240', abrasive: 'Silicon Carbide', backing: 'Sheet (Wet/Dry)' } },
  { name: 'Grinding Disc 125mm Metal',             category: 'Grinding Disc',        unit: 'pcs',       spec: { diameter_mm: '125', thickness_mm: '6', material: 'Metal / Mild Steel' } },
  { name: 'Cut-off Disc 125mm × 1.0mm',           category: 'Cut-off Disc',         unit: 'pcs',       spec: { diameter_mm: '125', thickness_mm: '1.0', material: 'Metal / Mild Steel' } },
  { name: 'Cut-off Disc 115mm Stainless',          category: 'Cut-off Disc',         unit: 'pcs',       spec: { diameter_mm: '115', thickness_mm: '1.0', material: 'Stainless Steel' } },
  { name: 'Flap Disc 125mm T29 — 40 Grit',        category: 'Flap Disc',            unit: 'pcs',       spec: { diameter_mm: '125', grit: '40', disc_type: 'T29 (Angled / Aggressive)', abrasive: 'Zirconia Alumina' } },
  { name: 'Flap Disc 125mm T29 — 80 Grit',        category: 'Flap Disc',            unit: 'pcs',       spec: { diameter_mm: '125', grit: '80', disc_type: 'T29 (Angled / Aggressive)', abrasive: 'Aluminium Oxide' } },
  { name: 'MIG Wire 0.8mm ER70S-6 (5kg)',         category: 'MIG Wire',             unit: 'spool',     spec: { diameter_mm: '0.8', alloy: 'ER70S-6 (Mild Steel)', spool_kg: '5' } },
  { name: 'MIG Wire 0.9mm ER70S-6 (15kg)',        category: 'MIG Wire',             unit: 'spool',     spec: { diameter_mm: '0.9', alloy: 'ER70S-6 (Mild Steel)', spool_kg: '15' } },
  { name: 'MIG Wire 0.9mm ER308L Stainless',      category: 'MIG Wire',             unit: 'spool',     spec: { diameter_mm: '0.9', alloy: 'ER308L (304 Stainless)', spool_kg: '5' } },
  { name: 'TIG Rod 2.4mm ER70S-2',               category: 'TIG Rod',              unit: 'kg',        spec: { diameter_mm: '2.4', alloy: 'ER70S-2 (Mild Steel)' } },
  { name: 'TIG Rod 2.4mm ER308L Stainless',      category: 'TIG Rod',              unit: 'kg',        spec: { diameter_mm: '2.4', alloy: 'ER308L (304 Stainless)' } },
  { name: 'TIG Rod 2.4mm ER4043 Aluminium',      category: 'TIG Rod',              unit: 'kg',        spec: { diameter_mm: '2.4', alloy: 'ER4043 (Aluminium)' } },
  { name: 'Stick Electrode E6013 3.2mm',          category: 'Stick Electrode',      unit: 'kg',        spec: { diameter_mm: '3.2', classification: 'E6013 (General Purpose)' } },
  { name: 'Stick Electrode E7018 3.2mm',          category: 'Stick Electrode',      unit: 'kg',        spec: { diameter_mm: '3.2', classification: 'E7018 (Low Hydrogen)' } },
  { name: 'Flux Core Wire 0.9mm Gasless',         category: 'Flux Core Wire',       unit: 'spool',     spec: { diameter_mm: '0.9', flux_type: 'E71T-GS (Gasless / Self-Shielded)' } },
  { name: 'Shielding Gas — 75/25 Ar/CO₂ (G)',    category: 'Shielding Gas',        unit: 'cylinder',  spec: { gas_type: '75% Ar / 25% CO₂ (MIG Steel — Standard)', cylinder_size: 'G (8.5 m³)' } },
  { name: 'Shielding Gas — Pure Argon (G)',       category: 'Shielding Gas',        unit: 'cylinder',  spec: { gas_type: 'Argon 100% (TIG / Aluminium MIG)', cylinder_size: 'G (8.5 m³)' } },
  { name: 'Nitrile Gloves — Medium',              category: 'Nitrile Gloves',       unit: 'box (100)', spec: { size: 'M', thickness_mil: '4 mil (Standard)' } },
  { name: 'Nitrile Gloves — Large',               category: 'Nitrile Gloves',       unit: 'box (100)', spec: { size: 'L', thickness_mil: '4 mil (Standard)' } },
  { name: 'Shop Towels (Blue Paper Roll)',         category: 'Shop Towels / Rags',   unit: 'rolls',     spec: { material: 'Paper (Blue Shop Roll)' } },
  { name: 'Masking Tape 24mm',                    category: 'Masking Tape',         unit: 'rolls',     spec: { width_mm: '24', tape_type: 'General Purpose' } },
  { name: 'Masking Tape 48mm (High-Temp)',         category: 'Masking Tape',         unit: 'rolls',     spec: { width_mm: '48', tape_type: 'High-Temp (Spray / Powder Coat)' } },
  { name: 'Electrical Tape — Black 19mm',         category: 'Electrical Tape',      unit: 'rolls',     spec: { colour: 'Black', width_mm: '19' } },
  { name: 'Cable Ties 300mm Black UV',            category: 'Cable Ties',           unit: 'pack',      spec: { length_mm: '300', colour: 'Black (UV-Stabilised)' } },
  { name: 'Heat Shrink 3:1 (Assorted)',           category: 'Heat Shrink',          unit: 'pack',      spec: { ratio: '3:1' } },
];
