// Every machine spec field the Tracker's search bar can match against —
// moved here from the old standalone Spec Search tab (now folded into the
// Tracker's own search box) so it's a shared, reusable list.
export const SPEC_SEARCH_FIELDS = [
  {k:"strokeType",       l:"Engine Type",                       u:""},
  {k:"plugGap",          l:"Spark Plug Gap",                    u:"mm"},
  {k:"coilType",         l:"Coil Type",                         u:""},
  {k:"primaryOhms",      l:"Primary Coil Resistance",           u:"ohms"},
  {k:"secondaryOhms",    l:"Secondary Coil Resistance",         u:"ohms"},
  {k:"starterType",      l:"Starter System",                    u:""},
  {k:"ropeDiameter",     l:"Starter Rope Diameter",             u:"mm"},
  {k:"ropeLength",       l:"Starter Rope Length",               u:"mm"},
  {k:"rBoltN",           l:"Recoil Bolt Count",                 u:""},
  {k:"rBoltSz",          l:"Recoil Bolt Diameter",              u:""},
  {k:"rBoltLen",         l:"Recoil Bolt Length",                u:"mm"},
  {k:"cylCount",         l:"Cylinder Count",                    u:""},
  {k:"firingOrder",      l:"Firing Order",                      u:""},
  {k:"valveTrain",       l:"Valve Train Type",                  u:""},
  {k:"camType",          l:"Cam Type",                          u:""},
  {k:"locknutSize",      l:"Rocker Arm Locknut Size",           u:""},
  {k:"iValveFace",       l:"Intake Valve Face Diameter",        u:"mm"},
  {k:"iValveStem",       l:"Intake Valve Stem Diameter",        u:"mm"},
  {k:"iValveLift",       l:"Intake Valve Lift",                 u:"mm"},
  {k:"iValveWeight",     l:"Intake Valve Weight",               u:"g"},
  {k:"eValveFace",       l:"Exhaust Valve Face Diameter",       u:"mm"},
  {k:"eValveStem",       l:"Exhaust Valve Stem Diameter",       u:"mm"},
  {k:"eValveLift",       l:"Exhaust Valve Lift",                u:"mm"},
  {k:"eValveWeight",     l:"Exhaust Valve Weight",              u:"g"},
  {k:"springFreeLen",    l:"Valve Spring Free Length",          u:"mm"},
  {k:"springOuterD",     l:"Valve Spring Outer Diameter",       u:"mm"},
  {k:"springWireD",      l:"Valve Spring Wire Diameter",        u:"mm"},
  {k:"springWeight",     l:"Valve Spring Weight",               u:"g"},
  {k:"ccSize",           l:"CC Size / Rating",                  u:"cc"},
  {k:"compression",      l:"Compression",                       u:"PSI"},
  {k:"idleRpm",          l:"Idle RPM (approx)",                 u:"rpm"},
  {k:"wotRpm",           l:"WOT RPM (approx)",                  u:"rpm"},
  {k:"plugType",         l:"Spark Plug Type",                   u:""},
  {k:"intakeValveClear", l:"Intake Valve Clearance",            u:"mm"},
  {k:"exhaustValveClear",l:"Exhaust Valve Clearance",           u:"mm"},
  {k:"intakeValveN",     l:"Valves per Intake",                 u:""},
  {k:"exhaustValveN",    l:"Valves per Exhaust",                u:""},
  {k:"iSpacing",         l:"Intake Stud Center Spacing",        u:"mm"},
  {k:"iStuds",           l:"Intake Studs per Side",             u:""},
  {k:"iBoltSz",          l:"Intake Stud Diameter",              u:""},
  {k:"iBoltLen",         l:"Intake Stud Length",                u:"mm"},
  {k:"eSpacing",         l:"Exhaust Stud Center Spacing",       u:"mm"},
  {k:"eStuds",           l:"Exhaust Studs per Side",            u:""},
  {k:"eBoltSz",          l:"Exhaust Stud Diameter",             u:""},
  {k:"eBoltLen",         l:"Exhaust Stud Length",               u:"mm"},
  {k:"iPW",              l:"Intake Port Width",                 u:"mm"},
  {k:"iPH",              l:"Intake Port Height",                u:"mm"},
  {k:"iPCond",           l:"Intake Port Condition",             u:""},
  {k:"iPNotes",          l:"Intake Port Notes",                 u:""},
  {k:"ePW",              l:"Exhaust Port Width",                u:"mm"},
  {k:"ePH",              l:"Exhaust Port Height",               u:"mm"},
  {k:"ePCond",           l:"Exhaust Port Condition",            u:""},
  {k:"ePNotes",          l:"Exhaust Port Notes",                u:""},
  {k:"pulseLoc",         l:"Pulse Port Location",               u:""},
  {k:"pulsePos",         l:"Pulse Port Position",               u:""},
  {k:"pulseOffset",      l:"Pulse Port Offset from Nearest Edge",u:"mm"},
  {k:"boreDiameter",     l:"Cylinder Bore Diameter",             u:"mm"},
  {k:"ptoDiameter",      l:"PTO Shaft Diameter",                 u:""},
  {k:"shaftType",        l:"Shaft Type",                         u:""},
  {k:"threadDir",        l:"Head Thread Direction",               u:""},
  {k:"threadSize",       l:"Head Thread Size",                    u:""},
  {k:"sprocketType",     l:"Sprocket Type",                       u:""},
  {k:"fuelSystem",       l:"Fuel System",                       u:""},
  {k:"cBrand",           l:"Carb Brand",                        u:""},
  {k:"cType",            l:"Carb Type",                         u:""},
  {k:"cModel",           l:"Carb Model",                        u:""},
  {k:"ecuModel",         l:"ECU Brand / Model",                 u:""},
  {k:"tbDiameter",       l:"Throttle Body Diameter",            u:"mm"},
  {k:"injectorCount",    l:"Fuel Injector Count",               u:""},
  {k:"injectorFlow",     l:"Injector Flow Rate",                u:"cc/min"},
  {k:"fuelRailPressure", l:"Fuel Rail Pressure",                u:"bar"},
  {k:"fuelPumpPressure", l:"Fuel Pump Pressure",                u:"bar"},
  {k:"tpsSensor",        l:"TPS Sensor",                        u:""},
  {k:"mapSensor",        l:"MAP Sensor",                        u:""},
  {k:"iatSensor",        l:"IAT Sensor",                        u:""},
  {k:"o2Sensor",         l:"O2 Sensor",                         u:""},
  {k:"iacSensor",        l:"IAC",                               u:""},
  {k:"year",             l:"Year",                              u:""},
  {k:"colour",           l:"Colour",                            u:""},
  {k:"bodyType",         l:"Body Type",                         u:""},
  {k:"driveConfig",      l:"Drive Configuration",               u:""},
  {k:"desc",             l:"Description",                       u:""},
  {k:"source",           l:"Source",                            u:""},
  {k:"pumpBrand",        l:"Pump Brand",                        u:""},
  {k:"pumpModel",        l:"Pump Model",                        u:""},
  {k:"pumpPsi",          l:"Pump Max PSI",                      u:"PSI"},
  {k:"pumpType",         l:"Pump Type",                         u:""},
  {k:"genWatts",         l:"Generator Rated Watts",             u:"W"},
  {k:"genVoltage",       l:"Generator Voltage",                 u:""},
  {k:"genFreq",          l:"Generator Frequency",               u:""},
  {k:"driveType",        l:"Drive Type",                        u:""},
  {k:"chainPitch",       l:"Chain Pitch",                       u:""},
  {k:"frontSprocket",    l:"Front Sprocket",                    u:"teeth"},
  {k:"rearSprocket",     l:"Rear Sprocket",                     u:"teeth"},
  {k:"transType",        l:"Transmission Type",                 u:""},
  {k:"forkType",         l:"Front Suspension Type",             u:""},
  {k:"forkDiameter",     l:"Fork Diameter",                     u:"mm"},
  {k:"rearShockType",    l:"Rear Suspension Type",              u:""},
  {k:"frontBrake",       l:"Front Brake Type",                  u:""},
  {k:"rearBrake",        l:"Rear Brake Type",                   u:""},
  {k:"tyreFront",        l:"Front Tyre Size",                   u:""},
  {k:"tyreRear",         l:"Rear Tyre Size",                    u:""},
  {k:"battVoltage",      l:"Battery Voltage",                   u:""},
  {k:"deckSize",         l:"Deck Size",                         u:"inches"},
  {k:"bladeType",        l:"Blade Type",                        u:""},
  {k:"bladeLength",      l:"Blade Length",                      u:"mm"},
  {k:"obShaftLength",    l:"Outboard Shaft Length",             u:""},
  {k:"obTransomHeight",  l:"Outboard Transom Height",           u:"mm"},
  {k:"obPropPitch",      l:"Propeller Pitch",                   u:"in"},
  {k:"obPropDiameter",   l:"Propeller Diameter",                u:"in"},
  {k:"obPropMaterial",   l:"Propeller Material",                u:""},
  {k:"obGearRatio",      l:"Outboard Gear Ratio",               u:""},
  {k:"obLowerUnitOilType",l:"Lower Unit Oil Type",              u:""},
  {k:"obAnodeMaterial",  l:"Anode Material",                    u:""},
  {k:"notes",            l:"Notes",                             u:""},
];
