export const TILE_FIELDS = [
  {k:"status",       l:"Status badge",        s:"",          types:null},
  {k:"strokeType",   l:"2T / 4T badge",       s:"",          types:null},
  {k:"year",         l:"Year",                s:"",          types:null},
  {k:"ccSize",       l:"CC size",             s:"",          types:null},
  {k:"compression",  l:"Compression",         s:"Comp:",     types:null},
  {k:"plugType",     l:"Spark plug type",     s:"Plug:",     types:null},
  {k:"plugGap",      l:"Plug gap",            s:"Gap:",      types:null},
  {k:"idleRpm",      l:"Idle RPM",            s:"Idle:",     types:null},
  {k:"wotRpm",       l:"WOT RPM",             s:"WOT:",      types:null},
  {k:"starterType",  l:"Starter",             s:"Start:",    types:null},
  {k:"fuelSystem",   l:"Fuel system",         s:"Fuel:",     types:null},
  {k:"cBrand",       l:"Carb brand",          s:"Carb:",     types:null},
  {k:"cModel",       l:"Carb model",          s:"",          types:null},
  {k:"driveType",    l:"Drive type",          s:"Drive:",    types:["Motorcycle","Scooter","Moped","Quad Bike","Go-kart","Jet Ski / PWC","Ride-on Mower"]},
  {k:"chainPitch",   l:"Chain pitch",         s:"Chain:",    types:["Motorcycle","Scooter","Moped","Quad Bike","Go-kart"]},
  {k:"tyreFront",    l:"Front tyre",          s:"F-tyre:",   types:["Motorcycle","Scooter","Moped","Quad Bike","Go-kart","Ride-on Mower","Lawnmower"]},
  {k:"tyreRear",     l:"Rear tyre",           s:"R-tyre:",   types:["Motorcycle","Scooter","Moped","Quad Bike","Go-kart","Ride-on Mower","Lawnmower"]},
  {k:"battVoltage",  l:"Battery voltage",     s:"Batt:",     types:["Motorcycle","Scooter","Moped","Quad Bike","Go-kart","Generator"]},
  {k:"pumpPsi",      l:"Pump PSI",            s:"PSI:",      types:["Pressure Washer"]},
  {k:"pumpBrand",    l:"Pump brand",          s:"Pump:",     types:["Pressure Washer"]},
  {k:"genWatts",     l:"Generator watts",     s:"Watts:",    types:["Generator"]},
  {k:"genVoltage",   l:"Generator voltage",   s:"V:",        types:["Generator"]},
  {k:"deckSize",     l:"Deck size",           s:"Deck:",     types:["Lawnmower","Ride-on Mower"]},
  {k:"bladeType",    l:"Blade type",          s:"Blade:",    types:["Lawnmower","Ride-on Mower"]},
  {k:"colour",       l:"Colour",              s:"",          types:["Vehicle","Motorcycle","Scooter","Moped","Quad Bike"]},
  {k:"bodyType",     l:"Body Type",           s:"",          types:["Vehicle","Motorcycle","Scooter","Moped"]},
  {k:"driveConfig",  l:"Drive Config",        s:"Drive:",    types:["Vehicle"]},
  {k:"obShaftLength",    l:"Shaft length",        s:"Shaft:",    types:["Outboard Motor"]},
  {k:"obPropPitch",     l:"Prop pitch",          s:"Pitch:",    types:["Outboard Motor"]},
  {k:"obPropDiameter",  l:"Prop diameter",       s:"Prop:",     types:["Outboard Motor"]},
  {k:"obGearRatio",     l:"Gear ratio",          s:"Ratio:",    types:["Outboard Motor"]},
  {k:"obAnodeMaterial", l:"Anode material",      s:"Anode:",    types:["Outboard Motor"]},
  {k:"source",       l:"Source",              s:"",          types:null},
  {k:"rage",         l:"Rage rating ☠️",       s:"",          types:null},
];
export const DEFAULT_TILE = ["status","strokeType","ccSize"];

export const ALL_BADGE_FIELDS = [
  {k:"status",        l:"Status",              s:"",         section:"General",   auto:true},
  {k:"strokeType",    l:"Engine Type",         s:"",         section:"General",   auto:true},
  {k:"rage",          l:"Rage Rating",         s:"",         section:"General",   auto:true},
  {k:"year",          l:"Year",                s:"",         section:"General"},
  {k:"colour",        l:"Colour",              s:"",         section:"General"},
  {k:"bodyType",      l:"Body Type",           s:"",         section:"General"},
  {k:"driveConfig",   l:"Drive Config",        s:"",         section:"General"},
  {k:"source",        l:"Source",              s:"",         section:"General"},
  {k:"ccSize",        l:"CC Size",             s:"CC:",      section:"Engine"},
  {k:"compression",   l:"Compression",         s:"Comp:",    section:"Engine"},
  {k:"idleRpm",       l:"Idle RPM",            s:"Idle:",    section:"Engine"},
  {k:"wotRpm",        l:"WOT RPM",             s:"WOT:",     section:"Engine"},
  {k:"cylCount",      l:"Cylinders",           s:"Cyl:",     section:"Engine"},
  {k:"boreDiameter",  l:"Bore",                s:"Bore:",    section:"Engine"},
  {k:"crankStroke",   l:"Stroke",              s:"Stroke:",  section:"Engine"},
  {k:"coolingType",   l:"Cooling",             s:"",         section:"Engine"},
  {k:"motorPower",    l:"Motor Power",         s:"kW:",      section:"Engine"},
  {k:"motorTorque",   l:"Motor Torque",        s:"Nm:",      section:"Engine"},
  {k:"evRange",       l:"Range",               s:"Range:",   section:"Engine"},
  {k:"plugType",      l:"Plug Type",           s:"Plug:",    section:"Ignition"},
  {k:"plugGap",       l:"Plug Gap",            s:"Gap:",     section:"Ignition"},
  {k:"coilType",      l:"Coil Type",           s:"Coil:",    section:"Ignition"},
  {k:"starterType",   l:"Starter",             s:"Start:",   section:"Starter"},
  {k:"ropeDiameter",  l:"Rope Diameter",       s:"Rope:",    section:"Starter"},
  {k:"fuelSystem",    l:"Fuel System",         s:"Fuel:",    section:"Fuel"},
  {k:"cBrand",        l:"Carb Brand",          s:"Carb:",    section:"Fuel"},
  {k:"cModel",        l:"Carb Model",          s:"",         section:"Fuel"},
  {k:"fuelTankCapacity",l:"Tank Capacity",     s:"Tank:",    section:"Fuel"},
  {k:"mixRatio",      l:"Mix Ratio",           s:"Mix:",     section:"Fuel"},
  {k:"turboFitted",   l:"Turbo",               s:"Turbo:",   section:"Fuel"},
  {k:"turboBoost",    l:"Boost",               s:"Boost:",   section:"Fuel"},
  {k:"chargingType",  l:"Charging",            s:"",         section:"Charging"},
  {k:"chargeVoltage", l:"Charge Voltage",      s:"",         section:"Charging"},
  {k:"chargeAmps",    l:"Charge Amps",         s:"A:",       section:"Charging"},
  {k:"driveType",     l:"Drive Type",          s:"Drive:",   section:"Drivetrain"},
  {k:"transType",     l:"Transmission",        s:"Trans:",   section:"Drivetrain"},
  {k:"gearCount",     l:"Gears",               s:"Gears:",   section:"Drivetrain"},
  {k:"chainPitch",    l:"Chain Pitch",         s:"Chain:",   section:"Drivetrain"},
  {k:"gearboxOilType",l:"Gearbox Oil",         s:"Oil:",     section:"Drivetrain"},
  {k:"forkType",      l:"Front Suspension",    s:"Fork:",    section:"Suspension"},
  {k:"rearShockType", l:"Rear Suspension",     s:"Rear:",    section:"Suspension"},
  {k:"frontBrake",    l:"Front Brake",         s:"F-Brk:",   section:"Brakes"},
  {k:"rearBrake",     l:"Rear Brake",          s:"R-Brk:",   section:"Brakes"},
  {k:"brakeFluidType",l:"Brake Fluid",         s:"BF:",      section:"Brakes"},
  {k:"tyreFront",     l:"Front Tyre",          s:"F:",       section:"Tyres"},
  {k:"tyreRear",      l:"Rear Tyre",           s:"R:",       section:"Tyres"},
  {k:"battVoltage",   l:"Battery Voltage",     s:"Batt:",    section:"Electrics"},
  {k:"batteryCCA",    l:"Battery CCA",         s:"CCA:",     section:"Electrics"},
  {k:"batteryAh",     l:"Battery Ah",          s:"Ah:",      section:"Electrics"},
  {k:"starterMotorType",l:"Starter Motor",     s:"Strt:",    section:"Electrics"},
  {k:"pumpBrand",     l:"Pump Brand",          s:"Pump:",    section:"Pump"},
  {k:"pumpPsi",       l:"Pump PSI",            s:"PSI:",     section:"Pump"},
  {k:"pumpType",      l:"Pump Type",           s:"",         section:"Pump"},
  {k:"genWatts",      l:"Watts",               s:"W:",       section:"Generator"},
  {k:"genVoltage",    l:"Gen Voltage",         s:"V:",       section:"Generator"},
  {k:"deckSize",      l:"Deck Size",           s:"Deck:",    section:"Blade"},
  {k:"bladeType",     l:"Blade Type",          s:"",         section:"Blade"},
  {k:"engineOilGrade",l:"Engine Oil",          s:"Oil:",     section:"Fluids"},
  {k:"engineOilCapacity",l:"Oil Capacity",     s:"",         section:"Fluids"},
  {k:"dryWeight",     l:"Dry Weight",          s:"kg:",      section:"Dimensions"},
  {k:"wheelbase",     l:"Wheelbase",           s:"WB:",      section:"Dimensions"},
  {k:"oilChangeInterval",l:"Oil Interval",     s:"Oil@:",    section:"Service"},
  {k:"majorServiceInterval",l:"Major Service", s:"Svc@:",    section:"Service"},
  {k:"trackedBrand",  l:"Brand",               s:"",         section:"Tracked"},
  {k:"trackedSubtype",l:"Machine Type",        s:"",         section:"Tracked"},
  {k:"operatingWeight",l:"Op. Weight",         s:"",         section:"Tracked"},
  {k:"trackType",     l:"Track Type",          s:"",         section:"Tracked"},
  {k:"hydPumpCount",  l:"Hyd Pumps",           s:"Pumps:",   section:"Tracked"},
];

export const BADGE_PALETTE = [
  ["#2a1200","#e8670a88","#e8670a"],
  ["#0e1a2a","#3a7bd588","#3a7bd5"],
  ["#0e200e","#3d9e5088","#3d9e50"],
  ["#200e0e","#c9404088","#c94040"],
  ["#180e28","#8b5cf688","#a78bfa"],
  ["#201a00","#d4a01788","#d4a017"],
  ["#0e1e1e","#2dd4bf88","#2dd4bf"],
  ["#1a1a1a","#55555588","#888888"],
];

export const TILE_COLOR_DEFAULTS = {
  status:"auto", strokeType:"auto", rage:"auto",
  ccSize:7, compression:1, plugType:2, plugGap:2,
  idleRpm:6, wotRpm:6, starterType:7, fuelSystem:1,
  cBrand:0, cModel:0, driveType:1, chainPitch:1,
  tyreFront:7, tyreRear:7, battVoltage:5, pumpPsi:3,
  pumpBrand:7, genWatts:5, genVoltage:5, deckSize:7,
  bladeType:7, source:7,
};

export const EXPAND_SECTIONS = [
  {k:"photos",       l:"Photos",                     types:null},
  {k:"desc",         l:"Description",                types:null},
  {k:"strokeType",   l:"Engine Type",                types:null},
  {k:"cylCount",     l:"Cylinder Count",             types:null},
  {k:"ccSize",       l:"CC Size / Rating",           types:null},
  {k:"compression",  l:"Compression",                types:null},
  {k:"plugType",     l:"Spark / Glow Plug Type",     types:null},
  {k:"plugGap",      l:"Plug Gap / Glow Resistance", types:null},
  {k:"coilType",     l:"Coil Type",                  types:null},
  {k:"primaryOhms",  l:"Coil Resistance",            types:null},
  {k:"starterType",  l:"Starter System",             types:null},
  {k:"ropeDiameter", l:"Starter Rope",               types:null},
  {k:"rBoltN",       l:"Recoil Bolts",               types:null},
  {k:"valveTrain",   l:"Valve Train",                types:["4-stroke"]},
  {k:"intakeValveClear",l:"Valve Clearances",        types:["4-stroke"]},
  {k:"iValveFace",   l:"Intake Valve Dims",          types:["4-stroke"]},
  {k:"eValveFace",   l:"Exhaust Valve Dims",         types:["4-stroke"]},
  {k:"springFreeLen",l:"Valve Springs",              types:["4-stroke"]},
  {k:"fasteners",    l:"Fastener Specs",             types:null},
  {k:"iPW",          l:"Port Dimensions",            types:null},
  {k:"pulseLoc",     l:"Pulse Port",                 types:["2-stroke"]},
  {k:"boreDiameter", l:"Cylinder Bore",              types:null},
  {k:"ptoDiameter",  l:"PTO / Output Shaft",         types:null},
  {k:"fuelSystem",   l:"Fuel System",                types:null},
  {k:"cBrand",       l:"Carb Details",               types:null},
  {k:"ecuModel",     l:"ECU / EFI Details",          types:null},
  {k:"tpsSensor",    l:"Sensors",                    types:null},
  {k:"driveType",    l:"Drivetrain",                 types:["Motorcycle","Scooter","Moped","Quad Bike","Go-kart","Jet Ski / PWC","Ride-on Mower"]},
  {k:"forkType",     l:"Suspension",                 types:["Motorcycle","Scooter","Moped","Quad Bike","Go-kart","Jet Ski / PWC"]},
  {k:"frontBrake",   l:"Brakes",                     types:["Motorcycle","Scooter","Moped","Quad Bike","Go-kart","Ride-on Mower"]},
  {k:"tyreFront",    l:"Tyres",                      types:["Motorcycle","Scooter","Moped","Quad Bike","Go-kart","Ride-on Mower","Lawnmower"]},
  {k:"battVoltage",  l:"Electrics",                  types:["Motorcycle","Scooter","Moped","Quad Bike","Go-kart","Generator"]},
  {k:"pumpBrand",    l:"Pump Details",               types:["Pressure Washer"]},
  {k:"genWatts",     l:"Generator Output",           types:["Generator"]},
  {k:"deckSize",     l:"Blade / Deck",               types:["Lawnmower","Ride-on Mower"]},
  {k:"lighting",     l:"Lighting",                   types:null},
  {k:"notes",        l:"Notes",                      types:null},
  {k:"serviceHistory",l:"Service History",           types:null},
];
export const DEFAULT_EXPAND = EXPAND_SECTIONS.map(f=>f.k);
export const getExpandFields = (type, strokeType) => EXPAND_SECTIONS.filter(f=>{
  if(!f.types) return true;
  return f.types.includes(type)||f.types.includes(strokeType);
});
export const getTileFields = (type) => TILE_FIELDS.filter(f=>!f.types||f.types.includes(type));

export const TABS = [
  {id:"tracker",   label:"📋 Tracker"},
  {id:"jobs",      label:"🗂 Jobs"},
  {id:"reminders", label:"🔔 Remind"},
  {id:"revenue",   label:"📊 Revenue", enthusiastOnly:true},
  {id:"parts",     label:"🔩 Parts"},
  {id:"clients",   label:"👤 Clients"},
  {id:"search",    label:"🔍 Search"},
  {id:"wiki",      label:"📖 Wiki"},
  {id:"users",     label:"👥 Users", teamOnly:true},
];

